CREATE TABLE `os_hikvision_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `device_id` int(10) unsigned DEFAULT NULL,
  `event_type` varchar(100) DEFAULT NULL,
  `event_state` varchar(50) DEFAULT NULL,
  `event_time` datetime DEFAULT NULL,
  `employee_no` varchar(100) DEFAULT NULL,
  `employee_name` varchar(150) DEFAULT NULL,
  `card_no` varchar(100) DEFAULT NULL,
  `major_event_type` int(11) DEFAULT NULL,
  `sub_event_type` int(11) DEFAULT NULL,
  `attendance_status` varchar(50) DEFAULT NULL,
  `verify_mode` varchar(50) DEFAULT NULL,
  `serial_no` bigint(20) DEFAULT NULL,
  `raw_payload` longtext NOT NULL,
  `payload_format` enum('XML','JSON','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `processing_status` enum('PENDING','PROCESSED','FAILED','IGNORED') NOT NULL DEFAULT 'PENDING',
  `processing_message` text DEFAULT NULL,
  `received_at` datetime NOT NULL,
  `processed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_serial_event` (`device_id`,`serial_no`),
  KEY `idx_device` (`device_id`),
  KEY `idx_employee` (`employee_no`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_status` (`processing_status`),
  KEY `idx_serial` (`serial_no`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci